# Install pre-commit hooks via
# pre-commit install

- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v2.2.3
  hooks:
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: double-quote-string-fixer
  - id: flake8

- repo: local
  hooks:

  - id: yapf
    name: Yet Another Python Formatter
    entry: yapf
    language: system
    types: [python]
    args: ["-i", "-vv"]

  # - id: travis-linter
  #   name: Travis Lint
  #   entry: travis lint
  #   files: .travis.yml
  #   language: ruby
  #   additional_dependencies: ['travis']
